server:
  port: 8888

spring:
  application:
    name: application

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Subproject-KTTKPM14-nhom07/CloudConfigServerApplication
          default-label: main
        bootstrap: false